# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short concise name for the course', max_length=144, unique=True, verbose_name='Course name')),
                ('course_difficulty', models.CharField(choices=[('EA', 'Easy (high school students)'), ('MO', 'Moderate (college entry)'), ('DI', 'Difficult (college students'), ('EX', 'Expert (college graduates)')], default='MO', max_length=2, verbose_name='Course difficulty')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Is the course visible')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category (e.g. biochemistry)', max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleCoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The answers text', verbose_name='Answer text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is the answer correct?')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short concise name for the question', max_length=144, verbose_name='Question name')),
                ('order', models.IntegerField(default=0, help_text='Determines the place of the question', verbose_name='Question name')),
                ('question_body', models.TextField(help_text='This field can contain markdown syntax', verbose_name='Question text')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_base.Question')),
            ],
            bases=('learning_base.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_base.Course', verbose_name="Question's course"),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('course', 'order')]),
        ),
        migrations.AddField(
            model_name='multiplecoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_base.MultipleChoiceQuestion', verbose_name="The answer's question"),
        ),
    ]
