# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ranking',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_difficulty',
            field=models.CharField(choices=[('EA', 'Easy (high school students)'), ('MO', 'Moderate (college entry)'), ('DI', 'Difficult (college students'), ('EX', 'Expert (college graduates)')], default='MO', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('course', 'rank')]),
        ),
    ]
