# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0001_initial'),
    ]

    operations = [
    migrations.RenameField('MultipleChoiceQuestion', 'answer_image', 'feedback_image'),
    ]
