# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0002_auto_20170809_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtext',
            name='text_field',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
