# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['module', 'order']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_difficulty',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='module_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='try',
            old_name='person',
            new_name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.IntegerField(choices=[(0, 'German/Deutsch'), (1, 'English')], default=1, verbose_name='Course Language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=models.TextField(blank=True, help_text='The feedback for the user after a sucessful answer', null=True, verbose_name='feedback'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('order', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('module', 'order')]),
        ),
    ]
