# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0004_auto_20170816_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationtext',
            old_name='question_image',
            new_name='image',
        ),
    ]
