# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0004_auto_20170707_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragAndDropQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_base.Question')),
            ],
            options={
                'abstract': False,
            },
            bases=('learning_base.question',),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('de', 'German/Deutsch'), ('en', 'English')], default='en', max_length=2, verbose_name='Course Language'),
        ),
    ]
