# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0006_auto_20170716_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(help_text='Name of the category (e.g. biochemistry)', max_length=144, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('category', 'name')]),
        ),
    ]
