# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0008_informationyoutube'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The answer text')),
                ('img', models.TextField(default='', help_text='The image for this answer')),
                ('correct', models.BooleanField(default=False, help_text='If this answer is correct')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', help_text='The Question of this quiz question.', verbose_name='quizQuestion')),
                ('image', models.TextField(default='', help_text='The image which is shown in this quiz')),
                ('course', models.ForeignKey(help_text='The Course of this question', on_delete=django.db.models.deletion.CASCADE, to='learning_base.Course')),
            ],
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_base.QuizQuestion'),
        ),
    ]
