# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0008_informationyoutube'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
