# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0009_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=2, verbose_name='Language'),
        ),
    ]
