# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0009_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name=b'Avatar of the User'),
        ),
    ]
