# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0010_auto_20170720_1144'),
        ('learning_base', '0009_auto_20170720_1109'),
    ]

    operations = [
    ]
