# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0010_auto_20170902_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='img',
            field=models.TextField(blank=True, default='', help_text='The image for this answer'),
        ),
    ]
