# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0012_multiplechoicequestion_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questionImage/%Y/%m/%d', verbose_name='The Image for the question'),
        ),
    ]
