# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0012_auto_20170906_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='color',
            field=models.CharField(default='#000000', help_text='Color that is used in the category context', max_length=7),
        ),
    ]
