# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0010_auto_20170901_2111'),
        ('learning_base', '0013_coursecategory_color'),
    ]

    operations = [
    ]
