# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0014_merge_20170908_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Avatar of the User'),
        ),
    ]
