# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0014_auto_20170726_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The Image for the question'),
        ),
    ]
