# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0016_auto_20170726_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer_image',
            field=models.CharField(blank=True, max_length=255, verbose_name='The Image for the answer'),
        ),
    ]
