# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0018_auto_20170802_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoiceanswer',
            old_name='answer_image',
            new_name='img',
        ),
    ]
