# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0018_auto_20171005_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationyoutube',
            name='text_field',
            field=models.TextField(blank=True, default=''),
        ),
    ]
