# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0019_auto_20171006_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CloneCademy', max_length=40)),
                ('image', models.TextField(default='')),
            ],
        ),
    ]
