# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0020_auto_20170802_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='img',
            field=models.TextField(blank=True, verbose_name='The Image for the answer'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer_image',
            field=models.TextField(blank=True, verbose_name='The Image for the question'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_image',
            field=models.TextField(blank=True, verbose_name='The Image for the question'),
        ),
    ]
