# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0020_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email to send system informations'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image',
            field=models.TextField(default='', verbose_name='Main image of the Homepage'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(default='CloneCademy', max_length=40, verbose_name='Title of the Homepage'),
        ),
    ]
