# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0021_auto_20171010_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
