# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0022_settings_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
