# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0001_initial'),
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tries', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_model.Profile')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_base.Question')),
            ],
        ),
        migrations.RenameModel(
            old_name='Completion',
            new_name='CourseCompletion',
        ),
    ]
