# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_base', '0002_auto_20170518_0940'),
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_base.Course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_model.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_base.Course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_model.Profile')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_base.Question')),
            ],
        ),
    ]
