# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0002_remove_profile_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningGroup',
        ),
    ]
