# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0003_delete_learninggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='try',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
